### ISSUE TITLE
GDBus.Error:org.gnome.Shell.LoadExtensionError: SyntaxError: illegal character

### ISSUE THREAD

**Issue by philippkunz** [TheKevJames/gnome-shell-extension-transmission-daemon#10]
i installed a fresh debian (https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-9.6.0-amd64-netinst.iso.torrent) with gnome and then tried to add transmission indicator from the on-off button on https://extensions.gnome.org/extension/365/transmission-daemon-indicator/, which failed.

only hint i have found so far is `/var/log/messages`:

> Nov 28 21:02:35 test gnome-software-service.desktop[858]: 20:02:35:0743 Gs  failed to call gs_plugin_app_install on shell-extensions: GDBus.Error:org.gnome.Shell.LoadExtensionError: SyntaxError: illegal character
> Nov 28 21:02:35 test gnome-software-service.desktop[858]: 20:02:35:0743 Gs  not saving error for user/*/*/shell-extension/transmission-daemon_patapon.info/*: GDBus.Error:org.gnome.Shell.LoadExtensionError: SyntaxError: illegal character

```
$ gnome-shell --version
GNOME Shell 3.22.3
```
so i downloaded https://extensions.gnome.org/extension-data/transmission-daemon%40patapon.info.v24.shell-extension.zip from https://extensions.gnome.org/extension/365/transmission-daemon-indicator/ by choosing the shell version according to what i've got above and the latest extension version offered and tried to install it with the teak tool, resulting in a similar error:

>Nov 28 21:22:42 test gnome-shell[719]: JS ERROR: Exception in callback for signal: extension-found: SyntaxError: illegal character @ /home/pk/.local/share/gnome-shell/extensions/transmission-daemon@patapon.info/extension.js:287

**Comment by philippkunz** [comment]
now i get this when trying to open the preferences, which i could not before

> There was an error loading the preferences dialog for Transmission Daemon Indicator:

```
SyntaxError: illegal character

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
```

and `/var/log/messages` reports
> Nov 28 22:14:17 test org.gnome.Software[507]: 21:14:17:0176 Gs  State change on user/*/*/shell-extension/transmissio
n-daemon_patapon.info/* from installed to available is not OK

**Comment by TheKevJames** [comment]
Very odd that you're getting this error! Backticks are call [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and should not be illegal. Which version of JavaScript is your GNOME Shell using?

**Comment by philippkunz** [comment]
Honestly, I don't really have much clue which version of what I really have or what it should be. This is also why I described exactly how I set up a fresh Debian in a VirtualBox VM from scratch. I would expect that the Transmission Daemon Indicator should work with the latest stable Debian. I hardly can imagine what I could have done wrong with that. Can you confirm it?

I absolutely agree that all the versions of all involved and relevant stuff has to be correct before evaluating any proposed changes such as my replacing the back ticks. I would also prefer to fix a dependency version.

I could not figure out the JavaScript version my shell is using. Can you give me an instruction how to find it?

**Comment by TheKevJames** [comment]
I unfortunately don't currently have the time to debug/replicate this too in-depth -- I'll try to get to it over the weekend. In the meantime, some additional information from you would be useful. Please send the results of running:
- `gjs --version`
- `gjs --jsversion`
- alt+f2 and type "lg" to open [Looking Glass](https://wiki.gnome.org/Projects/GnomeShell/LookingGlass) (hit escape to exit it), then enter the following and send the result of:
```
x = "bar"
`foo${x}`
```

**Comment by TheKevJames** [comment]
There might also be some relevant debugging information in Looking Glass.

Under the "extensions" tab:
![image](https://user-images.githubusercontent.com/3341822/49207869-096d2c00-f36b-11e8-8edd-551e76aba4c6.png)

Click "show errors":
![image](https://user-images.githubusercontent.com/3341822/49207888-1b4ecf00-f36b-11e8-97d8-76d289dff0ff.png)

Which hopefully will be less empty than the output on my machine.

**Comment by philippkunz** [comment]
```
pk@test:~$ gjs --version
Failed to open file '--version': No such file or directory
pk@test:~$ gjs --jsversion
Failed to open file '--jsversion': No such file or directory
pk@test:~$ 
```

maybe this could be helpful, just in case...

```
pk@test:~$ dpkg -l | grep javascript
ii  gir1.2-javascriptcoregtk-4.0:amd64    2.18.6-1~deb9u1                             amd64        JavaScript engine library from WebKitGTK+ - GObject introspection data
ii  gjs                                   1.46.0-1+b2                                 amd64        Mozilla-based javascript bindings for the GNOME platform
ii  libgjs0e                              1.46.0-1+b2                                 amd64        Mozilla-based javascript bindings for the GNOME platform
ii  libjavascriptcoregtk-4.0-18:amd64     2.18.6-1~deb9u1                             amd64        JavaScript engine library from WebKitGTK+
pk@test:~$ 
```


![image](https://user-images.githubusercontent.com/1410346/49209957-2d0c9280-f3bc-11e8-9426-aae4be62ba83.png)


Unfortunately my lg does not show the transmission daemon indicator extension and hence no additional information about an error. Might be because it already failed to install or start.

**Comment by TheKevJames** [comment]
@philippkunz As mentioned on #11, Version v27 was just released on extensions.gnome.org and should be live [pending review from a Gnome Shell maintainer](https://extensions.gnome.org/review/13922) -- it should include full support for Gnome version 3.34 and solve the above.

Closing this issue as resolved -- but please feel free to re-open or create a new issue if you run into problems with v27!
