### ISSUE TITLE
Broken on Gnome Shell 3.32

### ISSUE THREAD

**Issue by iexos** [TheKevJames/gnome-shell-extension-transmission-daemon#13]
`TypeError: this._construct is not a function`

A similar problem was solved here: https://github.com/TimurKiyivinski/gnome-shell-night-light-slider-extension/pull/45

**Comment by jmiskinis** [comment]
There's already a pull request issued for this. #12

**Comment by TheKevJames** [comment]
I've just merged #12 which should solve this -- I'll get the latest version onto gnome.org as soon as possible.
