### ISSUE TITLE
processList and processSession return errors

### ISSUE THREAD

**Issue by jmiskinis** [TheKevJames/gnome-shell-extension-transmission-daemon#17]
Hey everyone,

Thanks a lot for maintaining this great extension.

Unfortunately, it doesn't seem to work for me anymore on 5.2.14-arch2-1-ARCH with GNOME Shell 3.32.2. Below is the error messages produced after enabling the extension:

```
gnome-shell[1049]: invalid response to processSession: [object instance wrapper GIName:Soup.Message jsobj@0x7ff9051888b0 native@0x5630f69fcab0]
gnome-shell[1049]: invalid response to processList: [object instance wrapper GIName:Soup.Message jsobj@0x7ff905188af0 native@0x5630f6c5bc70]
gnome-shell[1049]: JS ERROR: TypeError: transmissionDaemonIndicator.updateStats is not a function
                                                 processStats@/home/jmi/.local/share/gnome-shell/extensions/transmission-daemon@patapon.info/extension.js:305:17
gnome-shell[1049]: JS ERROR: TypeError: transmissionDaemonIndicator.toggleTurtleMode is not a function
                                                 processSession@/home/jmi/.local/share/gnome-shell/extensions/transmission-daemon@patapon.info/extension.js:342:9
gnome-shell[1049]: JS ERROR: TypeError: transmissionDaemonIndicator.updateList is not a function
                                                 processList@/home/jmi/.local/share/gnome-shell/extensions/transmission-daemon@patapon.info/extension.js:293:9
```

I plan to work on the fixes a bit later. Posting this now in case someone else is experiencing the same issue,

**Comment by ghost** [comment]
Confirming the above on Arch with gnome-shell 3.34. Besides the aforementioned processList and processSession errors there's an additional `JS ERROR: Extension transmission-daemon@lab16: TypeError: this.torrentAdd is undefined`. Hope to see this lovely extension working again in the near future.

**Comment by TheKevJames** [comment]
@jmiskinis @glitsj16 Version v27 was just released on extensions.gnome.org and should be live [pending review from a Gnome Shell maintainer](https://extensions.gnome.org/review/13922) -- it should include full support for Gnome version 3.34 and solve the above.

Closing this issue as resolved -- but please feel free to re-open or create a new issue if you run into problems with v27!

**Comment by iexos** [comment]
Edit: sorry its working, I had to restart for the new version to take effect

**Comment by TheKevJames** [comment]
Awesome, thanks for confirming @iexos!
