### ISSUE TITLE
JS ERROR: TypeError: transmissionDaemonIndicator.connectionError is not a function

### ISSUE THREAD

**Issue by Bortechino** [TheKevJames/gnome-shell-extension-transmission-daemon#18]
Does not work in Fedora 31 Gnome 3,34 
Log error:

JS ERROR: TypeError: transmissionDaemonIndicator.connectionError is not a function
processStats@/home/****/.local/share/gnome-shell/extensions/transmission-daemon@patapon.info/extension.js:321:17

**Comment by TheKevJames** [comment]
Version v27 was just released on extensions.gnome.org and should be live [pending review from a Gnome Shell maintainer](https://extensions.gnome.org/review/13922) -- it should include full support for Gnome version 3,34.

Closing this issue as resolved -- but please feel free to re-open or create a new issue if you run into problems with v27!
