### ISSUE TITLE
Error meta is null on Gnome 3.38

### ISSUE THREAD

**Issue by squall77it** [TheKevJames/gnome-shell-extension-transmission-daemon#23]
The extension does not work anymore on Gnome 3.38, with the error TypeError: meta is null.
I have fixed it with this pull request  #22, the pull request  #21 have some graphical issue.

**Comment by tidux** [comment]
Ubuntu, Fedora, and Arch are all on 3.38 now so this is starting to become an issue for new installs.

**Comment by TheKevJames** [comment]
Should now be fixed, uploading v30 now.
