### ISSUE TITLE
Too many arguments to method..

### ISSUE THREAD

**Issue by ouafnico** [TheKevJames/gnome-shell-extension-transmission-daemon#4]
Hi

On gnome 3.26.2, with arch, I got this on journalctl -f (very often, like every 3 sec) :

mars 04 19:04:03 PORTABLE-NICO gnome-shell[947]: JS WARNING: [/home/nicolas/.local/share/gnome-shell/extensions/transmission-daemon@patapon.info/extension.js 185]: Too many arguments to method Soup.Message.set_request: expected 3, got 4

**Comment by tliron** [comment]
I had this problem, too, but it seems to be fixed in GitHub. The version in extensions.gnome.org (3.26 - 21) is out of date.

TheKevJames, are there plans to release this fix to extensions.gnome.org?

**Comment by ouafnico** [comment]
I still got it even in the github version :/

**Comment by TheKevJames** [comment]
@oaufnico @tliron I've just kicked off release [v22](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon/releases/tag/v22) which has to go through review by Gnome Shell Extension maintainers [here](https://extensions.gnome.org/review/8356) which fixes this issue.

Once v22 is on extensions.gnome.org (normal turnaround time seems to be <1 week), this issue should be resolved.
