### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by ViBE-HU** [TheKevJames/gnome-shell-extension-transmission-daemon#8]
I'm not really into github yet but I'm trying to figure out how things work. I just did a translation. But I dunno is it submitted or not. Could you help me?

**Comment by TheKevJames** [comment]
For sure! First off -- thanks a bunch for doing a translation, that's much appreciated.

All the translations need to be in [this folder](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon/tree/master/transmission-daemon%40patapon.info/locale). We currently have support for English (default) and localizations for Spanish, French, Italian, Portuguese, and Russian, each of which lives in their own folder.

To create a new localization, you can copy [this base file](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon/blob/master/transmission-daemon%40patapon.info/locale/gnome-shell-extension-transmission-daemon.pot) and fill in the `msgstr` values. [Here's an example of the Russian translation being added](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon/commit/87818e64b1bc342635c8f2be8cb9607d808990cf#diff-d1d58ec9860115e8ec3d14ad3de17eac).

If you need help submitting that localized file to this repo, let me know!

**Comment by ViBE-HU** [comment]
Thanks. The only problem is submitting. I'm not sure how to do.

**Comment by TheKevJames** [comment]
You can create [pull requests](https://yangsu.github.io/pull-request-tutorial/) from [your copy of the repo](https://github.com/ViBE-HU/gnome-shell-extension-transmission-daemon/tree/patch-1) to mine by clicking the "New pull request" button when you're looking at your [branch](https://git-scm.com/book/en/v1/Git-Branching-What-a-Branch-Is) on your copy of the repository. ie:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/3341822/47120996-caa16d80-d225-11e8-8445-2cd08f307a13.png">

After you click that button, you'll get a page which looks like this:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/3341822/47121063-02a8b080-d226-11e8-9fdf-39bd3c5463d6.png">

It will fill in some of the details by default, but you can adjust the title or body if you want to include more information. As soon as you click the "Create pull request" button there, your changes will be available for me to test/merge/etc.

**Comment by ViBE-HU** [comment]
Done. Thanks ^_^

**Comment by ViBE-HU** [comment]
Do you see my request? When could you release it?

**Comment by TheKevJames** [comment]
@ViBE-HU Sorry again this took so long to get to, thanks for the reminder message. I've merged the PR and will release it right away.
